spring.application.name=kartserver


# Server port
server.port=8761

# Disable Eureka client registration (this is a server)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka dashboard URL
#eureka.server.enable-self-preservation=false
