spring.application.name=gatedemo
server.port=8056
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
#eureka.instance.prefer-ip-address=false

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
app.security.secretKey="asdfghytrewrtyukjhgfghjgfdsaytrewehjhgfzgjjhgfdserdsdfghjkjhgfdhgfdseiuytrtyuuytre"